<?php

namespace Container99qsxda;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RKs2FboService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RKs2Fbo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RKs2Fbo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\AcceuilController::index' => ['privates', '.service_locator.gHAsjfE.App\\Controller\\AcceuilController::index()', 'getAcceuilControllerindexService', true],
            'App\\Controller\\AcceuilController::rechercherRecettes' => ['privates', '.service_locator.gHAsjfE.App\\Controller\\AcceuilController::rechercherRecettes()', 'getAcceuilControllerrechercherRecettesService', true],
            'App\\Controller\\GestionRecettesController::selectAll' => ['privates', '.service_locator.YRd.n4E.App\\Controller\\GestionRecettesController::selectAll()', 'getGestionRecettesControllerselectAllService', true],
            'App\\Controller\\RecetteController::index' => ['privates', '.service_locator.aF2VTXs.App\\Controller\\RecetteController::index()', 'getRecetteControllerindexService', true],
            'App\\Controller\\RecetteController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\RecetteController::new()', 'getRecetteControllernewService', true],
            'App\\Controller\\RecetteController::show' => ['privates', '.service_locator.S4F2L1Z.App\\Controller\\RecetteController::show()', 'getRecetteControllershowService', true],
            'App\\Controller\\RecetteController::edit' => ['privates', '.service_locator.MAZWmLn.App\\Controller\\RecetteController::edit()', 'getRecetteControllereditService', true],
            'App\\Controller\\RecetteController::delete' => ['privates', '.service_locator.MAZWmLn.App\\Controller\\RecetteController::delete()', 'getRecetteControllerdeleteService', true],
            'App\\Controller\\RecetteController::afficherUneRecette' => ['privates', '.service_locator.wznEwKw.App\\Controller\\RecetteController::afficherUneRecette()', 'getRecetteControllerafficherUneRecetteService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.g9BceMG.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UtilisateurController::show' => ['privates', '.service_locator.YcQzc6c.App\\Controller\\UtilisateurController::show()', 'getUtilisateurControllershowService', true],
            'App\\Controller\\UtilisateurController::edit' => ['privates', '.service_locator.LVPv12D.App\\Controller\\UtilisateurController::edit()', 'getUtilisateurControllereditService', true],
            'App\\Controller\\UtilisateurController::mesRecettes' => ['privates', '.service_locator.YcQzc6c.App\\Controller\\UtilisateurController::mesRecettes()', 'getUtilisateurControllermesRecettesService', true],
            'App\\Controller\\UtilisateurController::favoris' => ['privates', '.service_locator.hx0Vgan.App\\Controller\\UtilisateurController::favoris()', 'getUtilisateurControllerfavorisService', true],
            'App\\Controller\\UtilisateurController::deleteRecette' => ['privates', '.service_locator.MAZWmLn.App\\Controller\\UtilisateurController::deleteRecette()', 'getUtilisateurControllerdeleteRecetteService', true],
            'App\\Controller\\UtilisateurController::editRecette' => ['privates', '.service_locator.MAZWmLn.App\\Controller\\UtilisateurController::editRecette()', 'getUtilisateurControllereditRecetteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\AcceuilController:index' => ['privates', '.service_locator.gHAsjfE.App\\Controller\\AcceuilController::index()', 'getAcceuilControllerindexService', true],
            'App\\Controller\\AcceuilController:rechercherRecettes' => ['privates', '.service_locator.gHAsjfE.App\\Controller\\AcceuilController::rechercherRecettes()', 'getAcceuilControllerrechercherRecettesService', true],
            'App\\Controller\\GestionRecettesController:selectAll' => ['privates', '.service_locator.YRd.n4E.App\\Controller\\GestionRecettesController::selectAll()', 'getGestionRecettesControllerselectAllService', true],
            'App\\Controller\\RecetteController:index' => ['privates', '.service_locator.aF2VTXs.App\\Controller\\RecetteController::index()', 'getRecetteControllerindexService', true],
            'App\\Controller\\RecetteController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\RecetteController::new()', 'getRecetteControllernewService', true],
            'App\\Controller\\RecetteController:show' => ['privates', '.service_locator.S4F2L1Z.App\\Controller\\RecetteController::show()', 'getRecetteControllershowService', true],
            'App\\Controller\\RecetteController:edit' => ['privates', '.service_locator.MAZWmLn.App\\Controller\\RecetteController::edit()', 'getRecetteControllereditService', true],
            'App\\Controller\\RecetteController:delete' => ['privates', '.service_locator.MAZWmLn.App\\Controller\\RecetteController::delete()', 'getRecetteControllerdeleteService', true],
            'App\\Controller\\RecetteController:afficherUneRecette' => ['privates', '.service_locator.wznEwKw.App\\Controller\\RecetteController::afficherUneRecette()', 'getRecetteControllerafficherUneRecetteService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.g9BceMG.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UtilisateurController:show' => ['privates', '.service_locator.YcQzc6c.App\\Controller\\UtilisateurController::show()', 'getUtilisateurControllershowService', true],
            'App\\Controller\\UtilisateurController:edit' => ['privates', '.service_locator.LVPv12D.App\\Controller\\UtilisateurController::edit()', 'getUtilisateurControllereditService', true],
            'App\\Controller\\UtilisateurController:mesRecettes' => ['privates', '.service_locator.YcQzc6c.App\\Controller\\UtilisateurController::mesRecettes()', 'getUtilisateurControllermesRecettesService', true],
            'App\\Controller\\UtilisateurController:favoris' => ['privates', '.service_locator.hx0Vgan.App\\Controller\\UtilisateurController::favoris()', 'getUtilisateurControllerfavorisService', true],
            'App\\Controller\\UtilisateurController:deleteRecette' => ['privates', '.service_locator.MAZWmLn.App\\Controller\\UtilisateurController::deleteRecette()', 'getUtilisateurControllerdeleteRecetteService', true],
            'App\\Controller\\UtilisateurController:editRecette' => ['privates', '.service_locator.MAZWmLn.App\\Controller\\UtilisateurController::editRecette()', 'getUtilisateurControllereditRecetteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AcceuilController::index' => '?',
            'App\\Controller\\AcceuilController::rechercherRecettes' => '?',
            'App\\Controller\\GestionRecettesController::selectAll' => '?',
            'App\\Controller\\RecetteController::index' => '?',
            'App\\Controller\\RecetteController::new' => '?',
            'App\\Controller\\RecetteController::show' => '?',
            'App\\Controller\\RecetteController::edit' => '?',
            'App\\Controller\\RecetteController::delete' => '?',
            'App\\Controller\\RecetteController::afficherUneRecette' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UtilisateurController::show' => '?',
            'App\\Controller\\UtilisateurController::edit' => '?',
            'App\\Controller\\UtilisateurController::mesRecettes' => '?',
            'App\\Controller\\UtilisateurController::favoris' => '?',
            'App\\Controller\\UtilisateurController::deleteRecette' => '?',
            'App\\Controller\\UtilisateurController::editRecette' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AcceuilController:index' => '?',
            'App\\Controller\\AcceuilController:rechercherRecettes' => '?',
            'App\\Controller\\GestionRecettesController:selectAll' => '?',
            'App\\Controller\\RecetteController:index' => '?',
            'App\\Controller\\RecetteController:new' => '?',
            'App\\Controller\\RecetteController:show' => '?',
            'App\\Controller\\RecetteController:edit' => '?',
            'App\\Controller\\RecetteController:delete' => '?',
            'App\\Controller\\RecetteController:afficherUneRecette' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UtilisateurController:show' => '?',
            'App\\Controller\\UtilisateurController:edit' => '?',
            'App\\Controller\\UtilisateurController:mesRecettes' => '?',
            'App\\Controller\\UtilisateurController:favoris' => '?',
            'App\\Controller\\UtilisateurController:deleteRecette' => '?',
            'App\\Controller\\UtilisateurController:editRecette' => '?',
        ]);
    }
}
