<?php

namespace Container99qsxda;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcceuilControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gHAsjfE.App\Controller\AcceuilController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gHAsjfE.App\\Controller\\AcceuilController::index()'] = ($container->privates['.service_locator.gHAsjfE'] ?? $container->load('get_ServiceLocator_GHAsjfEService'))->withContext('App\\Controller\\AcceuilController::index()', $container);
    }
}
