<?php

namespace Container99qsxda;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGestionRecettesControllerselectAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YRd.n4E.App\Controller\GestionRecettesController::selectAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YRd.n4E.App\\Controller\\GestionRecettesController::selectAll()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recettes' => ['privates', 'App\\Repository\\RecetteRepository', 'getRecetteRepositoryService', true],
        ], [
            'recettes' => 'App\\Repository\\RecetteRepository',
        ]))->withContext('App\\Controller\\GestionRecettesController::selectAll()', $container);
    }
}
