<?php

namespace Container99qsxda;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecetteControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S4F2L1Z.App\Controller\RecetteController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S4F2L1Z.App\\Controller\\RecetteController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recette' => ['privates', '.errored..service_locator.S4F2L1Z.App\\Entity\\Recette', NULL, 'Cannot autowire service ".service_locator.S4F2L1Z": it needs an instance of "App\\Entity\\Recette" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'recetteRepository' => ['privates', 'App\\Repository\\RecetteRepository', 'getRecetteRepositoryService', true],
        ], [
            'recette' => 'App\\Entity\\Recette',
            'entityManager' => '?',
            'recetteRepository' => 'App\\Repository\\RecetteRepository',
        ]))->withContext('App\\Controller\\RecetteController::show()', $container);
    }
}
