<?php

namespace Container99qsxda;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecetteControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MAZWmLn.App\Controller\RecetteController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.MAZWmLn'] ?? $container->load('get_ServiceLocator_MAZWmLnService'));

        if (isset($container->privates['.service_locator.MAZWmLn.App\\Controller\\RecetteController::edit()'])) {
            return $container->privates['.service_locator.MAZWmLn.App\\Controller\\RecetteController::edit()'];
        }

        return $container->privates['.service_locator.MAZWmLn.App\\Controller\\RecetteController::edit()'] = $a->withContext('App\\Controller\\RecetteController::edit()', $container);
    }
}
