<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Recette extends \App\Entity\Recette implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'datePublication' => [parent::class, 'datePublication', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'detailRecette' => [parent::class, 'detailRecette', null],
        "\0".parent::class."\0".'difficulte' => [parent::class, 'difficulte', null],
        "\0".parent::class."\0".'etapes' => [parent::class, 'etapes', null],
        "\0".parent::class."\0".'favoris' => [parent::class, 'favoris', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'nombrePortions' => [parent::class, 'nombrePortions', null],
        "\0".parent::class."\0".'origine' => [parent::class, 'origine', null],
        "\0".parent::class."\0".'preparation' => [parent::class, 'preparation', null],
        "\0".parent::class."\0".'recetteCom' => [parent::class, 'recetteCom', null],
        "\0".parent::class."\0".'recettesNote' => [parent::class, 'recettesNote', null],
        "\0".parent::class."\0".'saison' => [parent::class, 'saison', null],
        "\0".parent::class."\0".'tempsDeCuison' => [parent::class, 'tempsDeCuison', null],
        "\0".parent::class."\0".'tempsDePreparation' => [parent::class, 'tempsDePreparation', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        "\0".parent::class."\0".'typeDePlat' => [parent::class, 'typeDePlat', null],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null],
        'datePublication' => [parent::class, 'datePublication', null],
        'description' => [parent::class, 'description', null],
        'detailRecette' => [parent::class, 'detailRecette', null],
        'difficulte' => [parent::class, 'difficulte', null],
        'etapes' => [parent::class, 'etapes', null],
        'favoris' => [parent::class, 'favoris', null],
        'id' => [parent::class, 'id', null],
        'image' => [parent::class, 'image', null],
        'nombrePortions' => [parent::class, 'nombrePortions', null],
        'origine' => [parent::class, 'origine', null],
        'preparation' => [parent::class, 'preparation', null],
        'recetteCom' => [parent::class, 'recetteCom', null],
        'recettesNote' => [parent::class, 'recettesNote', null],
        'saison' => [parent::class, 'saison', null],
        'tempsDeCuison' => [parent::class, 'tempsDeCuison', null],
        'tempsDePreparation' => [parent::class, 'tempsDePreparation', null],
        'titre' => [parent::class, 'titre', null],
        'typeDePlat' => [parent::class, 'typeDePlat', null],
        'utilisateur' => [parent::class, 'utilisateur', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
