<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'FavorisRecette' => [parent::class, 'FavorisRecette', null],
        "\0".parent::class."\0".'UserNotes' => [parent::class, 'UserNotes', null],
        "\0".parent::class."\0".'commentaires' => [parent::class, 'commentaires', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'listCourses' => [parent::class, 'listCourses', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        "\0".parent::class."\0".'recettes' => [parent::class, 'recettes', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        'FavorisRecette' => [parent::class, 'FavorisRecette', null],
        'UserNotes' => [parent::class, 'UserNotes', null],
        'commentaires' => [parent::class, 'commentaires', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'listCourses' => [parent::class, 'listCourses', null],
        'nom' => [parent::class, 'nom', null],
        'password' => [parent::class, 'password', null],
        'photo' => [parent::class, 'photo', null],
        'prenom' => [parent::class, 'prenom', null],
        'recettes' => [parent::class, 'recettes', null],
        'roles' => [parent::class, 'roles', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
