<?php

namespace ContainerBugnRZg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecetteControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aF2VTXs.App\Controller\RecetteController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aF2VTXs.App\\Controller\\RecetteController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recetteRepository' => ['privates', 'App\\Repository\\RecetteRepository', 'getRecetteRepositoryService', true],
            'noteRepository' => ['privates', 'App\\Repository\\NoteRepository', 'getNoteRepositoryService', true],
        ], [
            'recetteRepository' => 'App\\Repository\\RecetteRepository',
            'noteRepository' => 'App\\Repository\\NoteRepository',
        ]))->withContext('App\\Controller\\RecetteController::index()', $container);
    }
}
