<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBugnRZg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBugnRZg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBugnRZg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBugnRZg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBugnRZg\App_KernelDevDebugContainer([
    'container.build_hash' => 'BugnRZg',
    'container.build_id' => '17707603',
    'container.build_time' => 1742835481,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBugnRZg');
