<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_modules_es_array_for-each_js-node_modules_core-js_modules_es_obj-7bb33f.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
        'autre' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_modules_es_array_for-each_js-node_modules_core-js_modules_es_obj-7bb33f.js',
                '/build/autre.js',
            ],
            'css' => [
                '/build/autre.css',
            ],
        ],
        'showRecette' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_modules_es_array_for-each_js-node_modules_core-js_modules_es_obj-7bb33f.js',
                '/build/showRecette.js',
            ],
            'css' => [
                '/build/showRecette.css',
            ],
        ],
    ],
],

]];
